nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-d-runner.cjs
    spec: packages/dictionary-yarn-plugins/d-runner/bundles/@yarnpkg/plugin-d-runner.js

yarnPath: .yarn/releases/yarn-3.2.4.cjs
