service: dictionary-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  profile: dictionary

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
